---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-svc
  namespace: handson
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.appName }}