---
kind: Service
apiVersion: v1
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: spring-react-aks-app-ui
  name: {{ .Values.appName }}-svc
  namespace: handson
spec:
  loadBalancerIP: 20.189.123.161
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: {{ .Values.appName }}